#! /bin/sh
dest=$(realpath "../images")

for d in $(find . -type d -not -name "." -print)
do
    base=$(basename ${d})
    destdir=${dest}/${base}
    if [ ! -d ${destdir} ]
    then
        # Directory has never been rendered.
        echo "Rendering plantuml in ${d}..."
        mkdir -p ${destdir}
        plantuml -o ${destdir} ${d}
    elif [ $(ls -1 ${destdir} | wc -l) -ne $(ls -1 ${d} | wc -l) ]
    then
        # Rendered image count does not match plantuml source file count.
        echo "Updating Renders of plantuml in ${d}..."
        rm ${destdir}/*
        plantuml -o ${destdir} ${d}
    else
        # Directory already rendered.
        echo "Skipping ${d}."
    fi
done